services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: biblioteca
      POSTGRES_PASSWORD: biblioteca
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - biblioteca-data:/var/lib/postgresql/data

volumes:
  biblioteca-data:
